# - find Sqlite 3
# SQLITE3_INCLUDE_DIR - Where to find Sqlite 3 header files (directory)
# SQLITE3_LIBRARIES - Sqlite 3 library
# SQLITE3_FOUND - Set to TRUE if we found everything (library, includes and executable)

FIND_PATH   (SQLITE3_INCLUDE_DIR NAME sqlite3.h PATHS software/sqlite3/include NO_DEFAULT_PATH)
FIND_LIBRARY(SQLITE3_LIBRARIES NAME sqlite3 PATHS software/sqlite3/lib  NO_DEFAULT_PATH)

IF(SQLITE3_LIBRARIES AND SQLITE3_INCLUDE_DIR)
  SET(SQLITE3_FOUND TRUE)
ENDIF(SQLITE3_LIBRARIES AND SQLITE3_INCLUDE_DIR)

IF(SQLITE3_FOUND)
  IF(NOT SQLITE3_FIND_QUIETLY)
    MESSAGE(STATUS "Found Sqlite3 header file in ${SQLITE3_INCLUDE_DIR}")
    MESSAGE(STATUS "Found Sqlite3 libraries: ${SQLITE3_LIBRARIES}")
  ENDIF(NOT SQLITE3_FIND_QUIETLY)
ELSE(SQLITE3_FOUND)
  IF(SQLITE3_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find Sqlite3")
  ELSE(SQLITE3_FIND_REQUIRED)
    MESSAGE(STATUS "Optional package Sqlite3 was not found")
  ENDIF(SQLITE3_FIND_REQUIRED)
ENDIF(SQLITE3_FOUND)